export enum Permission {
  // Roles
  CREATE_ROLES = 1,
  DELETE_ROLES = 2,
  EDIT_ROLES = 3,
  VIEW_ROLES = 4,

  // Usuarios
  CREATE_USERS = 5,
  DELETE_USERS = 6,
  EDIT_USERS = 7,
  VIEW_USERS = 8,

  // Categorías
  CREATE_CATEGORIES = 9,
  DELETE_CATEGORIES = 10,
  EDIT_CATEGORIES = 11,
  VIEW_CATEGORIES = 12,

  // Productos
  CREATE_PRODUCTS = 13,
  DELETE_PRODUCTS = 14,
  EDIT_PRODUCTS = 15,
  VIEW_PRODUCTS = 16,

  // Depósitos
  CREATE_WAREHOUSES = 17,
  DELETE_WAREHOUSES = 18,
  EDIT_WAREHOUSES = 19,
  VIEW_WAREHOUSES = 20,

  // Zonas
  CREATE_ZONES = 21,
  DELETE_ZONES = 22,
  EDIT_ZONES = 23,
  VIEW_ZONES = 24,

  // Clientes
  CREATE_CLIENTS = 25,
  DELETE_CLIENTS = 26,
  EDIT_CLIENTS = 27,
  VIEW_CLIENTS = 28,

  // Proveedores
  CREATE_SUPPLIERS = 29,
  DELETE_SUPPLIERS = 30,
  EDIT_SUPPLIERS = 31,
  VIEW_SUPPLIERS = 32,

  // Compras
  CREATE_PURCHASES = 33,
  DELETE_PURCHASES = 34,
  EDIT_PURCHASES = 35,
  VIEW_PURCHASES = 36,

  // Ventas
  CREATE_SALES = 37,
  DELETE_SALES = 38,
  EDIT_SALES = 39,
  VIEW_SALES = 40,

  // Pedidos
  CREATE_ORDERS = 41,
  DELETE_ORDERS = 42,
  EDIT_ORDERS = 43,
  VIEW_ORDERS = 44,

  // Entregas
  CREATE_DELIVERIES = 45,
  DELETE_DELIVERIES = 46,
  EDIT_DELIVERIES = 47,
  VIEW_DELIVERIES = 48,

  // Movimientos de stock
  CREATE_STOCK_MOVEMENTS = 49,
  DELETE_STOCK_MOVEMENTS = 50,
  EDIT_STOCK_MOVEMENTS = 51,
  VIEW_STOCK_MOVEMENTS = 52,

  // Vehículos
  CREATE_VEHICLES = 53,
  DELETE_VEHICLES = 54,
  EDIT_VEHICLES = 55,
  VIEW_VEHICLES = 56,

  // Pagos
  CREATE_PAYMENTS = 57,
  DELETE_PAYMENTS = 58,
  EDIT_PAYMENTS = 59,
  VIEW_PAYMENTS = 60,

  // Cobros
  CREATE_COLLECTIONS = 61,
  DELETE_COLLECTIONS = 62,
  EDIT_COLLECTIONS = 63,
  VIEW_COLLECTIONS = 64,
}
